### ISSUE TITLE
MPC Phase 1 Website

### ISSUE THREAD

**Issue by Berk-Hardex** [bashash/ecobrex#2]
Right now, the mobile version of phase 1 website is not working properly.
That needs to be fixed, and the latest animation video should be added: https://youtu.be/iIqQKrUfth4

Thank you.

**Comment by bashash** [comment]
Fixed issue with commit 8ca808b3d61c2c3321d7e0e8bbe6cb2210afbeb7
Reason: custom.css became empty when transitioned to phase 2.

**Comment by bashash** [comment]
SOLVED
