### ISSUE TITLE
Phase 1 website - mobile version

### ISSUE THREAD

**Issue by Berk-Hardex** [bashash/ecobrex#3]
the below need to be fixed/changed:
1. Add the animation video to the mobile version
2. after submitting an application form, the text should read: "Thank you, your application has been received. One of our account managers will get in touch with you shortly." 
3. Change the phone number to "1-888-511-9944"

thank you.

**Comment by Berk-Hardex** [comment]
Changes #2 and #3 should be applied to the desktop version as well.

**Comment by bashash** [comment]
Under review

**Comment by bashash** [comment]
SOLVED

**Comment by Berk-Hardex** [comment]
Hi Reza,

The phone number is still the same on the desktop version.

**Comment by Berk-Hardex** [comment]
Mobile version:

* Cannot click "play" on the video. 
* The video has to be more visible. Pls see the attached screenshot. It would be great if you could add borders/outline to our video as shown there. 
![img-20160119-wa0000](https://cloud.githubusercontent.com/assets/16051625/12460903/fa0de5b0-bf6a-11e5-8216-3eeba51c81be.jpg)

**Comment by bashash** [comment]
SOLVED
